#!/usr/bin/env bash

if [[ ! -f /app/app/public/wp-content/plugins/sample-plugin ]]; then
	cd /app/app/public/wp-content/plugins
	git clone https://github.com/wp-cli/sample-plugin.git
fi

if [[ ! -f /app/app/public/unit-tests ]]; then
	cd /app/app/public
	wp core init-tests --dbname=wpcli_tests --dbuser=root --dbpass=secret_password
fi