#!/usr/bin/env bash

if [[ ! -f /opt/wordpress-tests ]]; then
	cd /vagrant/public
	svn co https://unit-tests.svn.wordpress.org/trunk wordpress-tests
	cd wordpress-tests
	cp -a wp-tests-config-sample.php wp-tests-config.php
	sed '/*Path to the WordPress codebase*/d' wp-tests-config.php
	sed '/*ABSPATH*/d' wp-tests-config.php
	mkdir tests
	wp -a /vagrant/.build/phpunit.bootstrap.php.sample tests/bootstrap.php
fi