#!/usr/bin/env bash

if [[ ! -f /app/app/runtimes/php/bin/phpcs ]]; then
  echo "Installing phpcs"
  /app/app/runtimes/php/bin/pear config-set php_dir /app/app/runtimes/php
  /app/app/runtimes/php/bin/pear config-set auto_discover 1
  /app/app/runtimes/php/bin/pear install PHP_CodeSniffer-1.4.5
  git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $(/app/app/runtimes/php/bin/pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
fi
echo "phpcs:  $(/app/app/runtimes/php/bin/phpcs --version)"