#!/usr/bin/env bash

if [[ ! -f /usr/bin/phpcs ]]; then
  echo "Installing phpcs"
  sudo pear config-set auto_discover 1
  sudo pear install PHP_CodeSniffer-1.4.5
  sudo git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
  phpcs --version
fi