#!/usr/bin/env bash

if [[ ! -f /usr/bin/phpunit ]]; then
  echo "Installing phpunit"
  sudo pear config-set auto_discover 1
  sudo pear channel-discover nikic.github.com/pear
  sudo pear install channel://nikic.github.com/pear/PHPParser-0.9.2
  sudo pear install pear.phpunit.de/DbUnit
  phpunit --version
fi
