#!/usr/bin/env bash

if [[ ! -f /usr/bin/phpmd ]]; then
  echo "Installing phpmd"
  sudo pear config-set auto_discover 1
  sudo pear channel-discover pear.phpmd.org
  sudo pear channel-discover pear.pdepend.org
  sudo pear install --alldeps phpmd/PHP_PMD
  phpmd --version
fi